name: Build and push images

on: 
  push:
    tags:
    - 'v*'

jobs:
  build-and-push:
    name: Build and push images
    if: ${{ github.event.base_ref == 'refs/heads/main' }}
    strategy:
      matrix:
        page: [1]
        # , 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
        page-total: [1]
      fail-fast: false
    runs-on: devcontainer-image-builder-ubuntu
    steps:
    - name: Free more space
      id: free_space 
      run: |
        set -e
        # Ensure enough space is available for build
        sudo apt-get autoremove -y
        sudo apt-get clean -y
        sudo rm -rf /usr/share/dotnet

    - name: Checkout
      id: checkout
      uses: actions/checkout@v1

    - name: Get tag name
      id: get_tag_name  
      run: echo "::set-output name=tag::$(echo "${{ github.ref }}" | grep -oP 'refs/tags/\K(.+)')"

    - name: Login to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.AZURE_REGISTRY }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and push
      id: build_and_push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REGISTRY: ${{ secrets.AZURE_REGISTRY }}
        REGISTRY_BASE_PATH: ${{ secrets.REGISTRY_BASE_PATH }}
      run: |
        set -e

        # Build and push images
        yarn install
        npm install -g @devcontainers/cli
        build/vscdc push  --page ${{ matrix.page }} \
                          --pageTotal ${{ matrix.page-total }} \
                          --release ${{ steps.get_tag_name.outputs.tag }} \
                          --github-repo ${{ github.repository }} \
                          --registry "$REGISTRY" \
                          --registry-path "$REGISTRY_BASE_PATH" 

  image-info:
    name: Trigger info extraction
    needs: [build-and-push]
    uses: devcontainers/images/.github/workflows/version-history.yml@main
    with:
      release: "${{ github.ref }}"
      cg: "false"
      push: "true"
      overwrite: "false"
    secrets: inherit
