name: Re-push image

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release branch or tag'
        required: true
        default: 'main'
      image:
        description: 'Image ID'
        required: true

jobs:
  build-and-push:
    name: Build and push images
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Free more space
      id: free_space 
      run: |
        set -e
        # Ensure enough space is available for build
        sudo apt-get autoremove -y
        sudo apt-get clean -y
        sudo rm -rf /usr/share/dotnet

    - name: Checkout ref
      id: checkout_ref
      uses: actions/checkout@v2
      with:
        path: 'ref'
        ref: ${{ github.ref }}
        
    - name: Checkout release
      id: checkout_release
      uses: actions/checkout@v2
      with:
        path: 'release'
        ref: ${{ github.event.inputs.release }}

    - name: Login to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.AZURE_REGISTRY }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
      
    - name: Build and push
      id: build_and_push
      env:
        REGISTRY: ${{ secrets.REGISTRY }}
        REGISTRY_BASE_PATH: ${{ secrets.REGISTRY_BASE_PATH }}
      run: |
        set -e

        # Setup build CLI
        cd "$GITHUB_WORKSPACE/ref"
        yarn install
        npm install -g @devcontainers/cli

        # Go to the release, symlink the build tool from ref since this is the version for the workflow
        cd "$GITHUB_WORKSPACE/release"
        rm -rf build node_modules
        ln -s "$GITHUB_WORKSPACE/ref/build" build
        ln -s "$GITHUB_WORKSPACE/ref/node_modules" node_modules

        build/vscdc push  --replace-images \
                          --release ${{ github.event.inputs.release }} \
                          --registry "$REGISTRY" \
                          --registry-path "$REGISTRY_BASE_PATH" \
                          ${{ github.event.inputs.image }}
